//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS_LOAN.Core.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VS_LOAN.Core.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực hiện.
        /// </summary>
        public static string Button_Action {
            get {
                return ResourceManager.GetString("Button_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Button_AddNew {
            get {
                return ResourceManager.GetString("Button_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string Button_Approve {
            get {
                return ResourceManager.GetString("Button_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không duyệt.
        /// </summary>
        public static string Button_DoNotBrowse {
            get {
                return ResourceManager.GetString("Button_DoNotBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không ký.
        /// </summary>
        public static string Button_DoNotSign {
            get {
                return ResourceManager.GetString("Button_DoNotSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải hồ sơ phát hành.
        /// </summary>
        public static string Button_Download_PublishBill {
            get {
                return ResourceManager.GetString("Button_Download_PublishBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu.
        /// </summary>
        public static string Button_GetData {
            get {
                return ResourceManager.GetString("Button_GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string Button_Pending {
            get {
                return ResourceManager.GetString("Button_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập lại.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string Button_ResetInput {
            get {
                return ResourceManager.GetString("Button_ResetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gởi duyệt áp dụng.
        /// </summary>
        public static string Button_SendPending {
            get {
                return ResourceManager.GetString("Button_SendPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string Button_View {
            get {
                return ResourceManager.GetString("Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string Date_FromDay {
            get {
                return ResourceManager.GetString("Date_FromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Date_Months {
            get {
                return ResourceManager.GetString("Date_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý.
        /// </summary>
        public static string Date_Quarters {
            get {
                return ResourceManager.GetString("Date_Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string Date_ToDay {
            get {
                return ResourceManager.GetString("Date_ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thực hiện.
        /// </summary>
        public static string DialogConfirmNo {
            get {
                return ResourceManager.GetString("DialogConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực hiện.
        /// </summary>
        public static string DialogConfirmYes {
            get {
                return ResourceManager.GetString("DialogConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc thực hiện?.
        /// </summary>
        public static string DialogConfirmYesNo {
            get {
                return ResourceManager.GetString("DialogConfirmYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền:.
        /// </summary>
        public static string Footer_BQ {
            get {
                return ResourceManager.GetString("Footer_BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ:.
        /// </summary>
        public static string Footer_DC {
            get {
                return ResourceManager.GetString("Footer_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại:.
        /// </summary>
        public static string Footer_DT {
            get {
                return ResourceManager.GetString("Footer_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ:.
        /// </summary>
        public static string Footer_LH {
            get {
                return ResourceManager.GetString("Footer_LH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm phát triển:.
        /// </summary>
        public static string Footer_NPT {
            get {
                return ResourceManager.GetString("Footer_NPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản:.
        /// </summary>
        public static string Footer_PB {
            get {
                return ResourceManager.GetString("Footer_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string Home_Index_A01 {
            get {
                return ResourceManager.GetString("Home_Index_A01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống kiểm duyệt hồ sơ.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản.
        /// </summary>
        public static string Menu_PB {
            get {
                return ResourceManager.GetString("Menu_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Menu_TC {
            get {
                return ResourceManager.GetString("Menu_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản pháp luật.
        /// </summary>
        public static string Menu_TL {
            get {
                return ResourceManager.GetString("Menu_TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy phép (*).
        /// </summary>
        public static string Menu_TL_GP {
            get {
                return ResourceManager.GetString("Menu_TL_GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản.
        /// </summary>
        public static string Menu_TL_VB {
            get {
                return ResourceManager.GetString("Menu_TL_VB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không thành công.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thành công.
        /// </summary>
        public static string Message_Succ {
            get {
                return ResourceManager.GetString("Message_Succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Message_Title {
            get {
                return ResourceManager.GetString("Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string NavBar_DX {
            get {
                return ResourceManager.GetString("NavBar_DX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hóa đơn điện tử.
        /// </summary>
        public static string NavBar_HTHDDT {
            get {
                return ResourceManager.GetString("NavBar_HTHDDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string NavBar_TTCN {
            get {
                return ResourceManager.GetString("NavBar_TTCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string NhanVien_Login_Button_DN {
            get {
                return ResourceManager.GetString("NhanVien_Login_Button_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống.
        /// </summary>
        public static string NhanVien_Login_DNHT {
            get {
                return ResourceManager.GetString("NhanVien_Login_DNHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công.
        /// </summary>
        public static string NhanVien_Login_Message_DangNhap_Error {
            get {
                return ResourceManager.GetString("NhanVien_Login_Message_DangNhap_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại tên đăng nhập hoặc mật khẩu.
        /// </summary>
        public static string NhanVien_Login_Message_DangNhap_Error_TDNORMK {
            get {
                return ResourceManager.GetString("NhanVien_Login_Message_DangNhap_Error_TDNORMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string NhanVien_Login_Message_DangNhap_Succ {
            get {
                return ResourceManager.GetString("NhanVien_Login_Message_DangNhap_Succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string NhanVien_Login_Password_Placeholder {
            get {
                return ResourceManager.GetString("NhanVien_Login_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hóa đơn điện tử.
        /// </summary>
        public static string NhanVien_Login_Span_HDDT {
            get {
                return ResourceManager.GetString("NhanVien_Login_Span_HDDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thông tin đăng nhập.
        /// </summary>
        public static string NhanVien_Login_Span_LTTDN {
            get {
                return ResourceManager.GetString("NhanVien_Login_Span_LTTDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống hóa đơn điện tử.
        /// </summary>
        public static string NhanVien_Login_Title {
            get {
                return ResourceManager.GetString("NhanVien_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string NhanVien_Login_UserName_Placeholder {
            get {
                return ResourceManager.GetString("NhanVien_Login_UserName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string NhanVien_Profile_QLND {
            get {
                return ResourceManager.GetString("NhanVien_Profile_QLND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thông tin cá nhân.
        /// </summary>
        public static string NhanVien_Profile_QLTTCN {
            get {
                return ResourceManager.GetString("NhanVien_Profile_QLTTCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng.
        /// </summary>
        public static string NhanVien_Profile_Title {
            get {
                return ResourceManager.GetString("NhanVien_Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string NhanVien_Profile_TT {
            get {
                return ResourceManager.GetString("NhanVien_Profile_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string NhanVien_UserProfile_Email {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string NhanVien_UserProfile_Gender {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string NhanVien_UserProfile_Gender_Girl {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Gender_Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string NhanVien_UserProfile_Gender_Man {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Gender_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string NhanVien_UserProfile_Info {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string NhanVien_UserProfile_Name {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        public static string NhanVien_UserProfile_Password {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu không thành công. Vui lòng kiểm tra lại.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error_Old {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận lại mất khẩu.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error_PassComfirm_Empty {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error_PassComfirm_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error_PassNew_Empty {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error_PassNew_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không đúng.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error_PassNewConform {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error_PassNewConform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu cũ.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Error_PassOld_Empty {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Error_PassOld_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string NhanVien_UserProfile_Password_PassConform {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_PassConform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string NhanVien_UserProfile_Password_PassNew {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_PassNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string NhanVien_UserProfile_Password_PassOld {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_PassOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        public static string NhanVien_UserProfile_Password_Succ {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Password_Succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string NhanVien_UserProfile_Phone {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt mật khẩu.
        /// </summary>
        public static string NhanVien_UserProfile_SetPassword {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài khoản.
        /// </summary>
        public static string NhanVien_UserProfile_Type {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string NhanVien_UserProfile_Type_Client {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Type_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string NhanVien_UserProfile_Type_Employee {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_Type_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string NhanVien_UserProfile_UserName {
            get {
                return ResourceManager.GetString("NhanVien_UserProfile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập vào chức năng này, xin vui lòng liên hệ với admin.
        /// </summary>
        public static string NoAuthorities_Title {
            get {
                return ResourceManager.GetString("NoAuthorities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (404) Không tìm thấy trang!.
        /// </summary>
        public static string NotPage_Index_404 {
            get {
                return ResourceManager.GetString("NotPage_Index_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với admin để được hỗ trợ!.
        /// </summary>
        public static string NotPage_Index_404_LH {
            get {
                return ResourceManager.GetString("NotPage_Index_404_LH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy hóa đơn.
        /// </summary>
        public static string Table_Action_Button_CancelBillCompletely {
            get {
                return ResourceManager.GetString("Table_Action_Button_CancelBillCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Table_ColAction {
            get {
                return ResourceManager.GetString("Table_ColAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị dòng _START_ đến dòng _END_ trên tổng số _TOTAL_ dòng.
        /// </summary>
        public static string Table_Info {
            get {
                return ResourceManager.GetString("Table_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị dòng _START_ đến dòng _END_ trên tổng số _TOTAL_ dòng.
        /// </summary>
        public static string Table_InfoEmpty {
            get {
                return ResourceManager.GetString("Table_InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị _MENU_ dòng mỗi trang.
        /// </summary>
        public static string Table_LengthMenu {
            get {
                return ResourceManager.GetString("Table_LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu.
        /// </summary>
        public static string Table_Paginate_First {
            get {
                return ResourceManager.GetString("Table_Paginate_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối.
        /// </summary>
        public static string Table_Paginate_Last {
            get {
                return ResourceManager.GetString("Table_Paginate_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau.
        /// </summary>
        public static string Table_Paginate_Next {
            get {
                return ResourceManager.GetString("Table_Paginate_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước.
        /// </summary>
        public static string Table_Paginate_Previous {
            get {
                return ResourceManager.GetString("Table_Paginate_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Table_Search {
            get {
                return ResourceManager.GetString("Table_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi không có dữ liệu hiển thị.
        /// </summary>
        public static string Table_ZeroRecords {
            get {
                return ResourceManager.GetString("Table_ZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xử lý.
        /// </summary>
        public static string Tabs_NoProcess {
            get {
                return ResourceManager.GetString("Tabs_NoProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xử lý.
        /// </summary>
        public static string Tabs_Processed {
            get {
                return ResourceManager.GetString("Tabs_Processed", resourceCulture);
            }
        }
    }
}
